# Generated by Django 4.0.6 on 2022-08-03 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('mint', '0001_initial'), ('mint', '0002_project'), ('mint', '0003_remove_project_id_project_project_end_date_and_more'), ('mint', '0004_rename_product_image_project_project_image'), ('mint', '0005_alter_project_project_date_and_more'), ('mint', '0006_task_project_twitter_follow_and_more'), ('mint', '0007_remove_project_twitter_follow_and_more'), ('mint', '0008_remove_task_projects_remove_task_twitter_follow_and_more'), ('mint', '0009_twitteruser_email_alter_project_project_end_date'), ('mint', '0010_alter_twitteruser_email'), ('mint', '0011_project_tweet_embed_html_and_more'), ('mint', '0012_rename_tweet_embed_html_project_twitter_embed_html'), ('mint', '0013_project_twitter_account_created_and_more'), ('mint', '0014_remove_project_twitter_account_created_date_and_more'), ('mint', '0015_alter_project_twitter_least_followers'), ('mint', '0016_alter_project_options'), ('mint', '0017_alter_project_options'), ('mint', '0018_alter_project_twitter_embed_html'), ('mint', '0019_alter_project_project_end_date_and_more'), ('mint', '0020_rename_task_winner_project_project_status'), ('mint', '0021_rename_twitter_like_link_project_twitter_tweet_link_and_more'), ('mint', '0022_rename_twitter_follow_link_project_twitter_follow_username'), ('mint', '0023_winner_project_winner_user_and_more'), ('mint', '0024_winner_username'), ('mint', '0025_remove_winner_id_winner_win_id'), ('mint', '0026_rename_win_id_winner_id'), ('mint', '0027_rename_id_winner_id'), ('mint', '0028_alter_winner_user'), ('mint', '0029_project_winners_delete_winner'), ('mint', '0030_rename_project_status_project_status'), ('mint', '0031_twitteruser_wallet_id_alter_project_project_end_date'), ('mint', '0032_twitteruser_accounnt_year_twitteruser_followers_and_more'), ('mint', '0033_rename_accounnt_year_twitteruser_account_year'), ('mint', '0034_alter_project_status'), ('mint', '0035_rename_twitter_account_years_project_twitter_account_months_and_more'), ('mint', '0036_emailnotification_alter_project_winners'), ('mint', '0037_emailnotification_heading_secondary_and_more'), ('mint', '0038_alter_emailnotification_content_and_more'), ('mint', '0039_rename_wallet_id_twitteruser_eth_wallet_id'), ('mint', '0040_project_wallet_type'), ('mint', '0041_twitteruser_sol_wallet_id'), ('mint', '0042_alter_project_wallet_type'), ('mint', '0043_alter_project_wallet_type'), ('mint', '0044_alter_project_wallet_type'), ('mint', '0045_alter_emailnotification_heading_and_more'), ('mint', '0046_project_email_required'), ('mint', '0047_alter_project_project_end_date'), ('mint', '0048_alter_twitteruser_eth_wallet_id_and_more'), ('mint', '0049_alter_twitteruser_eth_wallet_id'), ('mint', '0050_project_least_wallet_balance'), ('mint', '0051_alter_project_least_wallet_balance'), ('mint', '0052_project_end_hours_alter_project_project_end_date')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=255)),
                ('no_of_winners', models.PositiveIntegerField(default=1)),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('project_price', models.PositiveIntegerField(default=1)),
                ('project_link', models.URLField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_image', models.ImageField(upload_to='media/uploads/')),
                ('project_end_date', models.DateField(auto_now_add=True)),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_follow', models.BooleanField(default=False)),
                ('twitter_follow_username', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_like', models.BooleanField(default=False)),
                ('twitter_tweet_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_retweet', models.BooleanField(default=False)),
                ('twitter_embed_html', models.TextField(blank=True, editable=False, null=True)),
                ('twitter_account_created', models.BooleanField(default=False)),
                ('twitter_comment', models.BooleanField(default=False)),
                ('twitter_followers', models.BooleanField(default=False)),
                ('twitter_least_followers', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('twitter_account_months', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('twitter_tweet_id', models.BigIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-project_date'],
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('profile_image_url', models.CharField(max_length=255, null=True)),
                ('twitter_oauth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.twitterauthtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='registered', to='mint.project')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('eth_wallet_id', models.CharField(blank=True, max_length=42, null=True)),
                ('account_months', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('sol_wallet_id', models.CharField(blank=True, max_length=44, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='winners',
            field=models.ManyToManyField(blank=True, editable=False, related_name='winners', to='mint.twitteruser'),
        ),
        migrations.AddField(
            model_name='project',
            name='wallet_type',
            field=models.CharField(choices=[('NIL', 'Nil'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], default='NIL', max_length=3),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Congratulations, You have been selected', max_length=80)),
                ('heading', models.CharField(default='Congratulations!!!', max_length=60)),
                ('content', models.TextField(default='You have been picked as the winner of the project you registered for at twitter-minting, you can send us a mail to claim your price.', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('heading_secondary', models.CharField(default='You have been selected.', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='email_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='least_wallet_balance',
            field=models.FloatField(choices=[(0, '0'), (0.2, '0.2'), (0.5, '0.5'), (0.7, '0.7'), (1.0, '1.0')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='end_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(default=None, editable=False),
        ),
    ]
