# Generated by Django 4.0.5 on 2022-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('no_of_winners', models.IntegerField(default=0)),
                ('project_date', models.DateField()),
                ('project_price', models.IntegerField(default=0)),
                ('project_link', models.URLField(max_length=255)),
                ('project_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
