# Generated by Django 4.0.5 on 2022-06-18 13:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 6, 21)),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
