# Generated by Django 4.0.5 on 2022-06-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0003_remove_project_id_project_project_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='product_image',
            new_name='project_image',
        ),
    ]
