# Generated by Django 4.0.5 on 2022-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0004_rename_product_image_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
