# Generated by Django 4.0.5 on 2022-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0006_task_project_twitter_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='twitter_follow',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_follow_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_like',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_like_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_retweet',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_retweet_link',
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(blank=True, to='mint.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_follow_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_like_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='twitter_retweet_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_of_winners',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
