# Generated by Django 4.0.6 on 2022-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0006_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='twitter_mention_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0),
        ),
    ]
