# Generated by Django 4.0.6 on 2022-08-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0007_project_twitter_mention_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to='mint.twitteruser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter_mention_count',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
        ),
    ]
