# Generated by Django 4.0.5 on 2022-06-20 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0008_remove_task_projects_remove_task_twitter_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 6, 23)),
        ),
    ]
