# Generated by Django 4.0.5 on 2022-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0009_twitteruser_email_alter_project_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
