# Generated by Django 4.0.5 on 2022-06-21 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0010_alter_twitteruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tweet_embed_html',
            field=models.TextField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 6, 24)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='registered', to='mint.project'),
        ),
    ]
