# Generated by Django 4.0.6 on 2022-08-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mint', '0010_remove_twitteruser_referral_twitteruser_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='referred_by',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint.project')),
                ('referrals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refered_by', to='mint.twitteruser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
