# Generated by Django 4.0.5 on 2022-06-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0011_project_tweet_embed_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tweet_embed_html',
            new_name='twitter_embed_html',
        ),
    ]
