# Generated by Django 4.0.6 on 2022-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0011_remove_twitteruser_referred_by_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referrals',
        ),
        migrations.AddField(
            model_name='referral',
            name='referrals',
            field=models.ManyToManyField(blank=True, null=True, related_name='refered_by', to='mint.twitteruser'),
        ),
    ]
