# Generated by Django 4.0.5 on 2022-06-21 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0012_rename_tweet_embed_html_project_twitter_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='twitter_account_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_account_created_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 6, 21), null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_least_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
