# Generated by Django 4.0.6 on 2022-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0012_remove_referral_referrals_referral_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minimum_referral',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='referral_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='refered_by', to='mint.twitteruser'),
        ),
    ]
