# Generated by Django 4.0.5 on 2022-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0013_project_twitter_account_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='twitter_account_created_date',
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_account_years',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
