# Generated by Django 4.0.5 on 2022-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0014_remove_project_twitter_account_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='twitter_least_followers',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
