# Generated by Django 4.0.5 on 2022-06-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0015_alter_project_twitter_least_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_date', 'project_end_date')},
        ),
    ]
