# Generated by Django 4.0.5 on 2022-06-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0016_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_date']},
        ),
    ]
