# Generated by Django 4.0.5 on 2022-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0017_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='twitter_embed_html',
            field=models.TextField(blank=True, default=None, editable=False, null=True),
        ),
    ]
