# Generated by Django 4.0.5 on 2022-06-22 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0018_alter_project_twitter_embed_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 6, 25)),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter_embed_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
