# Generated by Django 4.0.5 on 2022-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0019_alter_project_project_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Winner',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
