# Generated by Django 4.0.5 on 2022-06-27 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0020_rename_task_winner_project_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='twitter_like_link',
            new_name='twitter_tweet_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twitter_retweet_link',
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_tweet_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 6, 30)),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter_follow_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
