# Generated by Django 4.0.5 on 2022-06-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0021_rename_twitter_like_link_project_twitter_tweet_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='twitter_follow_link',
            new_name='twitter_follow_username',
        ),
    ]
