# Generated by Django 4.0.5 on 2022-06-30 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0022_rename_twitter_follow_link_project_twitter_follow_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='win', to='mint.project'),
        ),
        migrations.AddField(
            model_name='winner',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='winner', to='mint.twitteruser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
    ]
