# Generated by Django 4.0.5 on 2022-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0023_winner_project_winner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
