# Generated by Django 4.0.5 on 2022-06-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0025_remove_winner_id_winner_win_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='win_id',
            new_name='ID',
        ),
    ]
