# Generated by Django 4.0.5 on 2022-06-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0026_rename_win_id_winner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='ID',
            new_name='id',
        ),
    ]
