# Generated by Django 4.0.5 on 2022-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0027_rename_id_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ManyToManyField(blank=True, to='mint.twitteruser'),
        ),
    ]
