# Generated by Django 4.0.5 on 2022-06-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0029_project_winners_delete_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='status',
        ),
    ]
