# Generated by Django 4.0.5 on 2022-07-01 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0030_rename_project_status_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(default=datetime.date(2022, 7, 5)),
        ),
    ]
