# Generated by Django 4.0.5 on 2022-07-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0031_twitteruser_wallet_id_alter_project_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='accounnt_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
