# Generated by Django 4.0.5 on 2022-07-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0032_twitteruser_accounnt_year_twitteruser_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='accounnt_year',
            new_name='account_year',
        ),
    ]
