# Generated by Django 4.0.5 on 2022-07-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0033_rename_accounnt_year_twitteruser_account_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
