# Generated by Django 4.0.5 on 2022-07-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0034_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='twitter_account_years',
            new_name='twitter_account_months',
        ),
        migrations.RenameField(
            model_name='twitteruser',
            old_name='account_year',
            new_name='account_months',
        ),
    ]
