# Generated by Django 4.0.5 on 2022-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0035_rename_twitter_account_years_project_twitter_account_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Hello', max_length=50)),
                ('heading', models.CharField(default='Hi', max_length=50)),
                ('content', models.CharField(default='Congratulations', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='winners',
            field=models.ManyToManyField(blank=True, editable=False, related_name='winners', to='mint.twitteruser'),
        ),
    ]
