# Generated by Django 4.0.5 on 2022-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0036_emailnotification_alter_project_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='heading_secondary',
            field=models.CharField(default='Hi', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='content',
            field=models.TextField(default='Congratulations', max_length=500),
        ),
    ]
