# Generated by Django 4.0.5 on 2022-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0037_emailnotification_heading_secondary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='content',
            field=models.TextField(default='You have been picked as the winner of the project you registered for at twitter-minting, you can send us a mail to claim your price.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='heading',
            field=models.CharField(default='Congratulations!!!', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='heading_secondary',
            field=models.CharField(default='You have been selected.', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(default='Congratulations, You have been selected', max_length=50),
        ),
    ]
