# Generated by Django 4.0.5 on 2022-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0039_rename_wallet_id_twitteruser_eth_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wallet_type',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('SOL', 'Solana')], default='ETH', max_length=3),
        ),
    ]
