# Generated by Django 4.0.5 on 2022-07-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0041_twitteruser_sol_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wallet_type',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('SOL', 'Solana')], default='NIL', max_length=3),
        ),
    ]
