# Generated by Django 4.0.5 on 2022-07-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0043_alter_project_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wallet_type',
            field=models.CharField(choices=[('NIL', 'Nil'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], default='NIL', max_length=3),
        ),
    ]
