# Generated by Django 4.0.5 on 2022-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0045_alter_emailnotification_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_required',
            field=models.BooleanField(default=True),
        ),
    ]
