# Generated by Django 4.0.5 on 2022-07-16 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0046_project_email_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
