# Generated by Django 4.0.5 on 2022-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0047_alter_project_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='eth_wallet_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='sol_wallet_id',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
