# Generated by Django 4.0.5 on 2022-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0048_alter_twitteruser_eth_wallet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='eth_wallet_id',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
