# Generated by Django 4.0.5 on 2022-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0049_alter_twitteruser_eth_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='least_wallet_balance',
            field=models.IntegerField(choices=[(0, '0'), (0.2, '0.2'), (0.5, '0.5'), (0.7, '0.7'), (1.0, '1.0')], default=0),
        ),
    ]
