# Generated by Django 4.0.5 on 2022-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0050_project_least_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='least_wallet_balance',
            field=models.FloatField(choices=[(0, '0'), (0.2, '0.2'), (0.5, '0.5'), (0.7, '0.7'), (1.0, '1.0')], default=0),
        ),
    ]
