# Generated by Django 4.0.6 on 2022-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0051_alter_project_least_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(default=None, editable=False),
        ),
    ]
